name: test-minimal

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Make snapshot folder
        run: |
          mkdir -p snapshots
          echo "created snapshots folder"
